version: '3.7'

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQLDB_DATABASE: minicloud
      MYSQL_PASSWORD: 123
      MYSQL_PORT: 3306

  minicloud-backend:
    build:
      context: minicloud_backend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./minicloud_backend/src:/home/node/app/src
      - ./minicloud_backend/nodemon.json:/home/node/app/nodemon.json
      - ./minicloud_backend/prisma:/home/node/app/prisma
      - ./minicloud_backend/ormconfig.json:/home/node/app/ormconfig.json
    container_name: minicloud_backend
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    command: npm run dev
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      BASE_URL: https//localhost/apis

  minicloud-web:
    build: minicloud_web
    volumes:
      - ./minicloud_web/assets:/app/assets
      - ./minicloud_web/components:/app/components
      - ./minicloud_web/pages:/app/pages
      - ./minicloud_web/plugins:/app/plugins
      - ./minicloud_web/static:/app/static
      - ./minicloud_web/store:/app/store
      - ./minicloud_web/nuxt.config.js:/app/nuxt.config.js
    ports:
      - "3000:3000"
    command: npm run start
    container_name: minicloud_web
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      BASE_URL: https://localhost/admin

volumes:
  db-data: {}
